# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: chat-server
# spec:
#   selector:
#     matchLabels:
#       app: chat-server
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: chat-server
#     spec:
#       containers:
#         - name: chat-server
#           image: node:14-alpine
#           command: ["node"]
#           args: ["index.js"]  # Cambia "server.js" por "index.js"
#           ports:
#             - containerPort: 3000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: chat-service
# spec:
#   selector:
#     app: chat-server
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 3000
#   type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app-container
          image: danielcaicedo8991/chat-app:2.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
spec:
  selector:
    app: chat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
